### ISSUE TITLE
wrong command on readme (2)

### ISSUE THREAD

**Issue by 1e165** [Gwynsav/gwostwriter#1]
You probably don't care about this repository anymore but i've noticed through my process of looking through neovim configurations that this repository link shown below is not your current username and not the repository's name:

    git clone https://github.com/gwynsav/gwostwrite.git ~/.config/nvim
    
Instead of that outdated link on the command, i request the usage of the following:

    git clone https://github.com/Gwynsav/gwostwriter.git $CONFIG_PATH

**Comment by sewergweller** [comment]
I do care! I honestly didn't notice the typo in the repo name... I wrote the README on a whim as sort of a placeholder and randomly got notified about this issue's existance like today through email... sorry for not reading this earlier.

About the username thing, it's case insensitive, both `https://github.com/gwynsav` and `https://github.com/Gwynsav` will link to my profile and repos.
